### ISSUE TITLE
DidInitAttrs Deprecations

### ISSUE THREAD

**Issue by koryteg** [alexlafroscia/ember-steps#73] opened 2017-07-06 17:55 UTC
in 2.6.0 and 2.13.0 there were deprecations in the component lifecycle hooks, as stated here: https://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks

currently seeing these warnings in the logs while using these components. I don't have time to make a PR for this right now. just noting this for now and will circle back when I have some time.

**Comment by alexlafroscia** [comment] 2017-07-06 23:53
Thanks for the heads up! I'll see if I can get to cleaning that up the weekend. If you do start on this, please let me know so that I know it's already being handled.

**Comment by alexlafroscia** [comment] 2017-07-08 20:34
I'm looking into this now.

**Comment by alexlafroscia** [comment] 2017-07-08 20:55
@koryteg are you using the latest version? I don't use the `didInitAttrs` hook anywhere, and the usage of the arguments to `didUpdateAttrs` and `didReceiveAttrs` have been removed...

**Comment by alexlafroscia** [comment] 2017-08-08 05:32
This shouldn't be happening on `v1.0.0` -- I can't reproduce. I'm going to close this issue, but please re-open it if the warnings are given on the latest version! I definitely want to stay ahead of the curve on any APIs this add-on uses that are going away in the future.

**Closed by alexlafroscia** 2017-08-08 05:32 UTC
