### ISSUE TITLE
onActivate/onDeactivate action hooks not triggering when navigating to step via query param

### ISSUE THREAD

**Issue by lougreenwood** [alexlafroscia/ember-steps#122] opened 2018-10-17 16:24 UTC
When using query params to manage step transitions as described below, it seems that the new `onActivate` & `onDeactivate` hooks aren't triggered.

https://alexlafroscia.com/ember-steps/latest/docs/cookbook/tabs/query-param

Actions work as expected with a standard `click=(action wizard.transition-to-next)` trigger

**Comment by lougreenwood** [comment] 2018-10-17 19:04
I'm guessing that maybe query params don't pass through `this.transitions.activate(destination)` and that might cause the issue?

https://github.com/alexlafroscia/ember-steps/pull/118/files#diff-9ce6ebc640032c935bb6652c775d8fbaR172

**Comment by alexlafroscia** [comment] 2018-10-17 19:15
Yup, the issue is that we added the hooks in a location where modifying `currentStep` doesn't actually hit them. @pepke41 and I are working on it!

**Comment by alexlafroscia** [comment] 2018-11-04 22:35
Should be all set and released in `6.1.2`!

**Closed by alexlafroscia** 2018-11-04 22:35 UTC
